### ISSUE TITLE
What other exporters / recorders should we have bundled by default?

### ISSUE THREAD

**Issue by tobz** [metrics-rs/metrics#10]
The list I came up with in my head was:
- log exporter (uses the `log` crate and its macros)
- HTTP server exporter (would expose an endpoint, probably use `hyper`)
- text recorder (organize keys by their scope hierarchy, looks like yaml sort of)
- Prometheus recorder (Prometheus exposition format, good for HTTP exporter to act as pull endpoint)

I think that covers a lot of basic needs, but I could be convinced to include others _by default_.  Totally not again more workspace crates for other exporters/recorders generally speaking: HTTP client (push), JSON recorder, etc.

**Comment by tobz** [comment]
Thinking on this more, I think we should have a JSON output (this lets people programmatically consume metrics)... but that other than that, we'd be decent for a 1.0 release.

I was thinking about statsd, but there's only one major service -- Datadog -- that I know of which _depends_ on statsd-based ingest.  So many of the popular tools/systems nowadays can use Prometheus, and have plugins to ingest it to their own format, that I hesitate to provide a bench of options.

This is where I think I'd like to mark the line that other observers should either be contributed or managed as 3rd party crates.

**Comment by mbellani** [comment]
Hi @tobz thanks for all the work on the metrics library. Since there's an issue open to add statsd support, is there a plan to add an interface to the library for things like timing/distribution? e.g. `record_timer!`or `record_distribution` and the recorder with a similar interface? As Dogstatsd does support those and those would probably be desired by the consumers if the target system is Datadog.

**Comment by tobz** [comment]
@mbellani This should already be possible.  For example, a `timing` metric in statsd already correlates to a histogram in `metrics`, and it should also be able to power a `histogram` or `distribution` metric in DogStatsD.

The only thing missing is a specific exporter implementation for statsd/DogStatsD.  Such an exporter is not likely to be something we implement ourselves: time is precious and limited and it should be an easy enough thing for someone to whip up over the course of a week.

In that vain, I'm gonna close this issue since we've more or less answered the initial question.  Feel free to open an issue, or come chat with us in Discord, if you have further thoughts!

**Comment by mbellani** [comment]
@tobz things like distributions and time metrics behave differently in systems like datadog e.g. distributions are aggregated on the server side vs on the agent whereas the histgorams are aggregated on agent side and it's really hard to get percentiles using histograms. One can use histogram interface to send timer/distribution but that would be somewhat misleading because Datadog supports that too. 

You can do something along the lines of `record_histogram!("timer.name", 100, "type"=>"timer)"` and let the recorder determine the type of metrics to send to the statsd agent but that feels happy, it would be really nice to have an interface along the lines of `record_timer!` etc.. to support such behavior. What do you think?

**Comment by tobz** [comment]
I think the answer is pretty straightforward, in this case: histograms in `metrics` are not histograms, technically speaking.

When you call `record_histogram!`, you data hits the `Recorder::record_histogram` method, and the exporter... does whatever it wants.  That might be treating it like a proper histogram, and bucketing the value, or maybe it involves treating it as a summary/sketch and aggregating locally.  Maybe it's a per-metric configuration that your exporter supports.

This has come up a few times, but histograms in `metrics` are named such because that's just the most common term, IMO.  From the terminology used, to the names of crates and libraries, "histograms" comes up time and time again.  Summary, sketch, distribution: all valid in their own right, but not the most common term.  Thus, we call them histograms in `metrics`, but they aren't necessarily histograms unless the exporter treats them as such.

With that said, while it may feel weird to call `record_histogram!` when you know you're using a DataDog exporter, and pushing it to a distribution, that's just sort of the sort of thing we can't avoid with a library based on generic terms.  There's always going to be some level of "oh, in metrics it's called this, but in the downstream system it's called that".  It's inevitable.

**Comment by mbellani** [comment]
> oh, in metrics it's called this, but in the downstream system it's called that
My point is that the underlying system supports all the types histograms/distribution/timer it's just not mapping a single histogram to timer or distribution.

**Comment by tobz** [comment]
Yeah, I think we might be talking past each other, or maybe we're just at an "agree to disagree" impasse: I'm not looking to add another fundamental metric type, or a macro that assigns specific meaning/context to an existing fundamental metric type, for the sake of being more accurately aligned to a specific downstream system.

If there are multiple types in the downstream system that a `metrics` histogram could map too -- timers if the unit is time, histograms/distributions otherwise -- then that's something the exporter needs to handle, or expose to allow the user to configure.

**Comment by mbellani** [comment]
that clarifies things for me, thanks a lot for quick responses and all the work here 🙇🏽‍♂️
