### ISSUE TITLE
Add record_timing and record_value to Recorder

### ISSUE THREAD

**Issue by sethwm** [metrics-rs/metrics#100]
Right now, both `timing!` and `value!` effectively drop their units and get merged into calls to `record_histogram`.  Many metrics systems want to disambiguate between timings and magnitudes.  Other unit disambiguation would be nice, but at the very least distinguishing between time and not-time would be useful.  One backwards compatible way to do that is to modify Recorder to look like:

```
pub trait Recorder {
...

/// assumed to be in nanos
fn record_timing(&self, key: Key, value: u64) {
    self.record_histogram(key, value);
}

fn record_value(&self, key: Key, value: u64) {
    self.record_histogram(key, value);
}

...
}
```

Then have `timing!` and `value!` call the correct corresponding method.  Implementors can choose to override `record_value` and `record_timing` if they wish.

**Comment by tobz** [comment]
We will likely solve this by allowing callers to register metrics with a given unit: #96.

I don't believe there is a workable design at the API level: providing time vs non-time specific methods still don't solve the issue of understanding the timebase of a timing measurement, which is a problem that comes up more often than being able to differentiate metrics by whether they're time or non-time.

We've also (in `main`/alpha releases) collapsed `timing!` and `value!` into `histogram!` to better map to the `Recorder` trait overall, which is why we're not keen to re-expand that.

I'll leave the ticket open for now for the sake of tracking. 👍
