### ISSUE TITLE
Panic when calling `snapshot` too frequently

### ISSUE THREAD

**Issue by FreeMasen** [metrics-rs/metrics#105]
Calling `controller.snapshot` can panic with the following message

```
thread 'main' panicked at 'attempt to subtract with overflow', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/metrics-util-0.3.1/src/streaming.rs:116:24
```

[Here is a minimal reproduction of the issue](https://github.com/FreeMasen/metrics-panic)

**Comment by tobz** [comment]
Oof!  Looks like a bug in our streaming compression implementation.

Should be fixable. :)

**Comment by tobz** [comment]
I've reproduced the issue, albeit with fuzzing vs your MVCE, which actually never triggered for me, weirdly enough.

The fix is straightforward, but will take a small amount of time as we haven't yet spun up any backport branches: the stuff in `main` is v2/non-backportable changes so we can't just cut a patch release and be done with it.

I'll update this ticket once all of that happens.

**Comment by tobz** [comment]
Very delayed response here: while this is no longer a problem in the current alpha releases, I've pushed out `metrics-util@0.3.2` which contains the aforementioned fix.  You should be able to `cargo update` yourselves to pull it in since `metrics-runtime@0.12.1` has a dependency on `^0.3`.
