### ISSUE TITLE
Histogram/Value with Timestamps

### ISSUE THREAD

**Issue by jose-pr** [metrics-rs/metrics#124]
Possibility to record/add value to a histogram with a timestamp, so that it is then possible to limit histogram to a specific time period and/or quantity,  enabling the creation of meters for timeframes, such as throughput for 5minutes, 15minutes , 1hour etc.

Add to Recorder trait:
 `fn record_timestamped_histogram(&self, key: Key, value: u64, timestamp: u64);`
or
 `fn record_timestamped_histogram(&self, key: Key, value: u64, timestamp: Option<u64>);`

Macro:
`timestamped_value!("value.key", val, timestamp)`
or
`timestamped_value!("value.key", val)` timestamp defaults to now.

Maybe implement as:
```
pub enum Measurement {
    Counter(u64),
    Gauge(i64),
    Histogram(StreamingIntegers),
    HistogramWithTimestamp(
        StreamingIntegers, //Values
       StreamingIntegers //Timestamp in nanos of values
    )
}
```

**Comment by tobz** [comment]
We haven't officially released it yet, but the code in `main` involves a major refactor of `metrics` and the surrounding crates.  In those versions, an exporter could capture this data itself because they control the recording interface, but practically speaking, it would only work for capturing the current time.  It wouldn't support taking metrics that occurred in the past.

`metrics` is designed specifically for emitting measurements immediately, not at a different point-in-time, or taking them in after-the-fact, so I'm not willing to change the API/macros in this way at this time.
