### ISSUE TITLE
Document macros with usage examples

### ISSUE THREAD

**Issue by MOZGIII** [metrics-rs/metrics#132]
I found that the macros (`counter!`, `gauge!`, `histogram!`, etc) can be documented, and then `rust-analyzer` is capable to pick up the documentation and show it very conveniently.

Currently, it's a bit difficult to work with macros, as you have to look up or remember the signature to use. If we add the expected signature and add usage examples to macros doc-comments it will be way easier to utilize.

**Comment by tobz** [comment]
What would this look like in practice?  Right now, we _do_ have docs for the macros under `metrics/src/lib.rs` where we re-export them.

**Comment by MOZGIII** [comment]
> What would this look like in practice? Right now, we _do_ have docs for the macros under `metrics/src/lib.rs` where we re-export them.

`rust-analyzer` doesn't catch them :(

**Comment by tobz** [comment]
No sweat!

Can you take another look on `main`? I pushed an update that removes `proc-macro-hack`, which I think should lead to the re-export stuff not getting garbled and letting the IDE better pick up on the existing documentation.  That was my hope, at least. :)

**Comment by tobz** [comment]
Very delayed reply, but combing through older issues on the repo...

It _seems_ like this is related to how we re-export the macros, since looking at the `test` proc macro from `tokio`, it appears that they document it where it's actually defined, versus how we document it which is at the re-export site.

I'm a little iffy on putting the code examples into `metrics-macros` but that may be the path forward here.  Going to try one small thing to see if we can re-export the macros in a slightly different way to carry along the documentation in a way that makes `rust-analyzer` happy, but otherwise I'll probably just move the documentation to `metrics-macros` and call it a day.

**Comment by tobz** [comment]
It turns out that achieving this is not super easy.

The best I've been able to manage to do is to get `rust-analyzer` to display a simple doc comment on hover while the "full" documentation for the procedural macros is generated in the `metrics` crate.

Unfortunately, we cannot put all of the documentation into `metrics-macros` itself: this would prevent the code examples in the documentation from being runnable, because `metrics-macros` has no idea what crate `metrics` is when running the expanded macros.

Currently, the way `rustdoc` works, documentation can be added to public re-exports which is how we currently achieve the documentation we have in `metrics` for the macros.  This documentation is actually _prepended_ to the documentation defined on the item itself.  Since `rust-analyzer` seems to only load the documentation of the procedural macro itself, this lets us provide some very minimal documentation on the proc macro -- the one-line description and a link to the `metrics` docs -- which can be the bridge to the real documentation, but it results in the documentation in `metrics` looking like:

```
Registers a counter.

...

Registers a counter.

See [`metrics::register_counter`] for more details and examples.
```

This isn't the _worst_ but it's kind of ugly and confusing.  I'm going to try and reach out to the `rustdoc` team, and potentially the `rust-analyzer` folks, to see if there's something that can be done... maybe hide the proc macro docs from being appended via `rustdoc`, or maybe `rust-analyzer` actually could figure out to use the documentation on the re-export, etc.

**Comment by tobz** [comment]
Closing this as I don't think we're likely to achieve anything better than what we've currently got.
