### ISSUE TITLE
No way to specify histogram buckets

### ISSUE THREAD

**Issue by alexforster** [metrics-rs/metrics#167]
The `register_histogram!` macro should allow the optional specification of buckets. This would allow both the Prometheus "histogram" and "summary" types to be modeled: when buckets are specified, the metric is a histogram; when not specified, the metric is a summary.

Alternatively, an explicit fourth "summary" type could be introduced. It would replace the existing "histogram" type, and the histogram type would then have the concept of buckets added.

References:

 * [Prometheus exposition format spec](https://prometheus.io/docs/instrumenting/exposition_formats/)
 * ["Histograms and Summaries"](https://prometheus.io/docs/practices/histograms/)

**Comment by tobz** [comment]
We already expose the ability to specify buckets directly on the Prometheus exporter itself, which switches the output from summaries to histograms, as you referenced:

- [`PrometheusBuilder::set_buckets`](https://docs.rs/metrics-exporter-prometheus/0.1.0/metrics_exporter_prometheus/struct.PrometheusBuilder.html#method.set_buckets)
- [`PrometheusBuilder::set_buckets_for_metric`](https://docs.rs/metrics-exporter-prometheus/0.1.0/metrics_exporter_prometheus/struct.PrometheusBuilder.html#method.set_buckets_for_metric)

Shipping specific metadata -- like what buckets to use -- is too much coupling to shove into the core macros / trait, IMO.  We consciously avoided that because it doesn't matter for some exporters -- forwarders, etc -- and could lead to suboptimal ergonomics: "oh, I defined these buckets here, but the XYZ application isn't respecting them!"  Exporters have the raw data, so that's where we want these choices being made.

**Comment by alexforster** [comment]
I'm confused about your point on coupling: the choice of buckets is a fundamental property of histograms. What is the point of adding `register_*` macros in 0.13 if not to decouple the definition of metrics from exporters? The need for a `set_buckets_for_metric` method on the exporter is particularly indicative of tight coupling between the register macros and the exporters.

If I'm following this logic, I believe the same "too specific metadata" argument can be made about the introduction of `Unit`, which Prometheus has no concept of.

**Comment by tobz** [comment]
Registration macros -- `register_counter!`, etc -- are designed specifically for declaring metrics upfront for things that are updated infrequently.  Their position in the chain is a natural one for declaring metadata, no doubt, and so that's why we support declaring units and descriptions when using them.

Units and descriptions are general enough that I think their existence require no justification: working with dimensionless units is just not a thing most people using `metrics` will ever do.  Defining a description allows libraries in the ecosystem to hoist context about a metric up into the exporter, given that the express goal is `metrics` is to be like `log`, which means being sprinkled throughout libraries who have no idea what exporter will be used.

But on to the meat of the issue: histograms in `metrics` are not Prometheus histograms.  This is a language thing, really.  In software, we talk about histograms and summaries/sketches/distributions almost interchangeably, even though they have separate and distinct usages.  Calling it a histogram was a deliberate choice to use the terminology familiar with most people without declaring that doing so meant you got an honest-to-god histogram that couldn't have percentiles/quantiles pulled from it.  People usually want percentiles/quantiles.

It's a bit of an opinionated stance, I admit,.  Considering the above, and that the macros are already at a point of complexity that isn't great i.e. accepting 3 parameters as-is means potential ergonomics footgun...  all of these factors make it very hard for me to consider changing them as such, even acknowledging that it leads to toil in usage for some cases.

**Comment by rc-andres** [comment]
I know this was already marked as closed but just to drop in my two cents: I was also looking for a way to specify buckets for histograms. 

The `metrics_util` crate has a `Histogram` struct whose naming seem to imply a coupling with the `histogram*` macros/functions in this crate. However one cannot create a `Histogram` without having pre-defined buckets which is why it seems like there is a gap in between using histograms in the macros/recorder vs the `Histogram` struct in the util crate. 

The problem of leaving it up to the recorder's implementation of how to define buckets is that oftentimes the spot that emits the metric has the most knowledge of what are the expected bucket ranges. The application that creates/sets the recorder just wants to offload the metrics that were emitted and isn't fully aware of the best bucket ranges for each individual metric which makes it hard to pre-define. 

We can find ways around this but it still feels like there is a gap somewhere. That being said maybe the gap isn't on buckets themselves but perhaps something more general like a context, but that gets even harder to define so 🤷🏽‍♂️

**Comment by tobz** [comment]
Yeah, this is sort of a functional limitation of the model we've chosen, which is that the macros are meant to be opaque entry points into the system, and shouldn't be making their own decisions around presentation.

To flip your example around: what if you're trying to utilize the metric emitted by a dependency, that chose poorly-spaced histogram buckets, to debug a performance issue? Now you have little to no insight into the long tail where your problem may actually exist.

I do recognize that this is a little tricky and I don't disagree that most applications have a reasonable idea about what the buckets ought to be, and often, it's advantageous/cleaner to couple that with or close to the metric callsite.

Practically speaking, we also don't store histogram values in an actual honest-to-god histogram internally: we simply track the raw values for a given series.  Specifying the histogram bins would mean nothing, for example, with a theoretical Datadog exporter because Datadog doesn't support histograms, while it does support distributions and those merely require raw samples.  At the time, when designing this, there was a preponderance of evidence that letting the exporters specify this stuff would provide the best balance of flexibility vs obviousness.

As well, we really only call it "histogram" because it felt like the least technical thing we could call it that wasn't "timing" but still indicated how the data would eventually be used.

**Comment by Veetaha** [comment]
I do understand the @tobz concern about the library hardcoding the buckets to poor ranges, and this would clearly be a problem if we were to give the responsibility of defining the buckets to the sole call site of `[register]_histogram!()`. However, that problem can be solved (and in fact is already solved today) by just having the API for overriding the buckets choice made by the user of `[register]_historgram!()` at the exporter crate level.

It means the histogram macros could define the buckets, but those will be just the "default buckets", not the "ultimate buckets" that everyone is deemed to use at the end in their Grafana dashboards.

So for example if the library defines a histogram like this:

```rust
histogram!("metric_name", [0.01, 0.1, 0.3, 0.5, 1.0, 5.0], 99.9);
```

and the concrete application that uses the library with this metric finds these default buckets unreasonable, then they could override them with:
```rust
PrometheusBuilder()
    .set_buckets_for_metric(Matcher::Full("metric_name".to_owned()), [0.0001, 0.001, 0.01, 0.1])
    .install()
    .expect("BUG: couldn't initialize metrics");
```
