### ISSUE TITLE
OpenCensus / OpenTelemetry compatibility

### ISSUE THREAD

**Issue by kazimuth** [metrics-rs/metrics#19]
[OpenCensus](https://opencensus.io/) is an open source initiative for automated metric harvesting, basically this crate for a bunch of languages. (It also does distributed tracing which is a different thing.)

It might be worth looking at its API for inspiration, see what capabilities it offers.

It also has the [OpenCensus service](https://opencensus.io/service/), which is a service you can export to via gRPC, which can then export to [like 17 other telemetry things](https://opencensus.io/service/exporters/). Might be worth providing an exporter to that service.

Note: There's also [OpenTelemetry](https://opentelemetry.io/) which is going to be the sequel to OpenCensus but is currently mostly vaporware.

**Comment by tobz** [comment]
Yeah, I've been waiting for OpenTelemetry to materialize before I look further into integrating with that whole ecosystem.  I also want us to have metric tagging support since it seems like we're well and truly not going back to the statsd/Graphite style of dot-notation metrics, which is really just a stopgap for `metrics` at the moment in terms of providing dimensionality.

I'll leave this open as a marker issue to remember to look back into this down the line. 👍

**Comment by jtescher** [comment]
The beginnings of OpenTelemetry for rust are coming together in https://github.com/open-telemetry/opentelemetry-rust, the metrics API is still very much is flux but would be great to get perspective from you folks as the API is designed in https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/api-metrics.md

**Comment by tobz** [comment]
Going to close this for now.  I think the interfaces that exist on either side should be sufficient if someone decides that they want to make the integration a reality.
