### ISSUE TITLE
Register macros add unused values in Prometheus export.

### ISSUE THREAD

**Issue by BratSinot** [metrics-rs/metrics#193]
For example:
```
use metrics::{increment_counter, register_counter};
use metrics_exporter_prometheus::{PrometheusHandle, PrometheusBuilder, PrometheusRecorder};

lazy_static::lazy_static! {
    static ref RECORDER: PrometheusRecorder = PrometheusBuilder::new()
        .build();
    static ref HANDLE: PrometheusHandle = RECORDER.handle();
}

fn main() {
    metrics::set_recorder(&*RECORDER).unwrap();

    register_counter!("http_requests_total", "Incoming Requests");
    increment_counter!("http_requests_total", "handler" => "/");

    println!("{}", HANDLE.render());
}
```
Give us these output:
```
# HELP http_requests_total Incoming Requests
# TYPE http_requests_total counter
http_requests_total 0 # HERE
http_requests_total{handler="/"} 1
```
Any other way to add describe without using zero-value?

**Comment by tobz** [comment]
This is a tricky one, at least based on the current API, because yeah, registering a metric (to provide a description) is meant to ensure it shows up in the output.

We could conceivably split out "describing" a metric from "registering" a metric, but I'll have to think about it a little more.  The main problem is that every time we split out a specific operation, it means a minimum of three new methods in the `Recorder` API.

**Comment by tobz** [comment]
This should be addressed by #240 as we've introduced new macros/methods on `Recorder` for specifically describing a metric but not actually registering it.

That said, there's no release (yet) that includes #240.

**Comment by tobz** [comment]
This is now released as part of `metrics-exporter-prometheus@v0.8.0`, but realistically, it's driven by the change to the macros themselves that were changed in `metrics@v0.18.0`.

**Comment by BratSinot** [comment]
Thanks! Everything work fine now!

**Comment by tobz** [comment]
Awesome. 🙏
