### ISSUE TITLE
Refactor `Key` to be a struct

### ISSUE THREAD

**Issue by kazimuth** [metrics-rs/metrics#23]
Refactoring idea: redefine Key to be similar to `common::MetricIdentifier`, and just use that everywhere from `metrics-core` up:

```rs
#[derive(Clone, Copy, PartialEq, Eq, Hash)]
struct Key<'_> {
   kind: MetricType,
   name: Cow<str>,
   scope: Cow<str>,
   labels: Cow<[(Cow<str>, Cow<str>)]>,
}

#[derive(Clone, Copy, PartialEq, Eq, Hash)]
enum MetricType {
    Counter,
    Gauge,
    Histogram
}
```

This would make label support easy + turn a bunch of APIs from `record_xyz(name, value)` to just `record(Key {name, value, scope, labels})`. It would also hopefully make defining the `Ingest` trait really easy (#21).

**Comment by tobz** [comment]
Yeah, having `Key` as a struct would make easier to collapse the trait that facade recorders need to implement with the idea of a generic ingest trait, since you can't have generics in static mutables, and that's the main reason we have `metrics-facade` defining its own trait.

Would need to sketch this out in a PR, I think, to get a better feel for it.

**Comment by tobz** [comment]
This happened in #27.
