### ISSUE TITLE
Sanitize metric names/labels during recording.

### ISSUE THREAD

**Issue by tobz** [metrics-rs/metrics#29]
At some point, we'll likely want to sanitize metric names and labels when recording them.

For instance, curly braces are meaningful in the Prometheus exposition format, so we'd likely want to turn those into something else.  Same with equal signs, etc etc.

Basically, we just need to do a pass over existing recorders to try and help make sure a rogue metric name doesn't blow things up.  Either way, a user would have to fix their usage of reserved characters, or change the metric if they don't like our replacement... but at least with the latter, they'd still have metrics flowing.

**Comment by jean-airoldie** [comment]
I think ideally you would want to used a stricter type than a string so that the checking is enforced at the creation of the metrics. Specifically a type that implements `TryFrom<&str>` & `FromStr` and that `Deref` to a `str`.

I wrote [`something similar`] in another lib, but that derefs to a `CStr`.

[`something similar`]: https://docs.rs/libzmq/0.1.22/src/libzmq/group.rs.html#45-47

**Comment by tobz** [comment]
Yeah, this is a two part process, I think:

- make list of, say, the top 6-7 metric "systems" and their format/requirements for metric names
- sanitize metric names correspondingly

**Comment by tobz** [comment]
Closing as we've implemented this in #95.

We now force all metric names to be alphanumeric + underscore + colon + period.  This provides a clear invariant to exporters knowing what to expect from a metric name and what they may need to compensate for.

This won't be backported to 0.12 as we're now working towards a 1.0 release in the very near future, and is currently only available on main, although I'll likely cut new alpha releases of all crates within a week, which will include this change.
