### ISSUE TITLE
Support for 'process metrics' (in the Prometheus sense)

### ISSUE THREAD

**Issue by reivilibre** [metrics-rs/metrics#292]
Prometheus has a convention of ['process metrics'](https://prometheus.io/docs/instrumenting/writing_clientlibs/#process-metrics), which are usually provided by the language-specific Prometheus library used in the application (not the application itself). I don't know if other metric systems do, but in my experience these are very useful, even alongside application-specific metrics.

It seems like the kind of thing that would be useful if it was available from an 'official' `metrics` crate (maybe `metrics-process`?), so that any application could have an easy time to install these metrics.

Considering I'd quite like (most of) these metrics myself, I'm tempted to start off an implementation.

Would this be accepted as a PR into this repository?

#291 seems like it would be a useful prerequisite, but for now a timer-based implementation could be used (perhaps spawning a task onto `tokio`, since the `metrics-exporter-prometheus` crate already uses Tokio for its background work and it should be less heavyweight than a full-fat thread.)

**Comment by tobz** [comment]
I think this functionality would be best as a separate crate.  There's no particular reason to couple it to the Prometheus exporter.

I'm probably a soft "no" on taking a PR for such a crate and having it live in the main `metrics` repository because it will almost assuredly become a maintenance burden, given the vastness of potential host metrics a user may want to collect, and doing it in a cross-platform way.

However, I'd be happy to link to such a crate from the docs as part of a cohesive strategy for `metrics` being a way to collect host and application metrics all in one

**Comment by reivilibre** [comment]
Makes sense; thanks!
