### ISSUE TITLE
How to avoid data loss on shutdown

### ISSUE THREAD

**Issue by jorendorff** [metrics-rs/metrics#308]
:wave: Hi, everyone. I work on code search at GitHub and we ❤️ `metrics`.

We have a panic hook that does `metrics::increment_counter!("panic");`. But we've found that this increment often doesn't make it to the server.

I think our recorder (we're using [`metrics-expoter-statsd`](https://github.com/github/metrics-exporter-statsd/)) buffers output and the process is exiting without flushing the buffers. Dropping the recorder before exiting the process would be sufficient, for us. Is there a way to do that? Is there something else I should be doing? I couldn't figure it out from the readme or API docs.

If this already exists, I think there's already a great place to document it (under "Getting started -> In executables") and I'd be happy to write that up.

**Comment by tobz** [comment]
Hello there!

Reading through your description, I see where you're coming from.

At a high level, there is no way, currently, to drop the recorder as it's installed in such a way that callers can take a `'static` reference to it, which means that installing a recorder requires either a `&'static dyn Recorder` or an owned `R: Recorder` which we box and then leak, in order to fulfill the `'static` requirement.

Most of the ways around this that I can think of would depend on the exporter being able to give back a handle, of some sort, to the caller that is creating/installing the exporter such that the handle would act as the drop guard that could be used to force a flush, etc, when the process is exiting.

**Comment by tobz** [comment]
Another thought is potentially doing something with `Arc<T>`/`Weak<T>` where the weak reference can be wrapped and installed as the recorder and then then `Arc<T>` could be held as a drop guard so that the true `R` (being `R: Recorder`) could be legitimately dropped and have the `Drop` impl added directly, and not need to write a custom drop guard, with all of the requisite synchronization.

This would still necessitate holding that drop guard directly, rather than the installed recorder being able to handle this, but it would at least be something we could provide a generalized wrapper for.

**Comment by tobz** [comment]
@jorendorff A bit late, but... I have a PR up for a drop guard primitive, as described in my last comment on this issue, that I'm curious if you would be interested in. At least ,if nothing else, I'm curious to see if this _would_ have helped solve your problem (if you already found a solution and don't care to switch away from it).

**Comment by aig787** [comment]
Hey @tobz, not OP, but I was facing this same issue with an influx/grafana cloud exporter and fixed it using this approach. Any plans to cut a new release?

**Comment by tobz** [comment]
Yeah, I'm a little behind on releasing the currently outstanding changes. Hoping to be able to do so this week.

**Comment by tobz** [comment]
@aig787 Released in `metrics-util@v0.15.1`.

**Comment by tobz** [comment]
Closing this issue as this use case should be generically solved via #362.
