### ISSUE TITLE
Accessing metrics from the prometheus recorder

### ISSUE THREAD

**Issue by bschwind** [metrics-rs/metrics#341]
Hi, I have a situation where I'm not sure how best to proceed. I'm currently using `metrics-exporter-prometheus` to expose a simple HTTP scrape target for prometheus.

I'm now wanting to expose those same metrics to other parts of my application.

Should I:

* Create a new `Recorder`, and use something like `Fanout` to distribute metrics to both?
* Modify `PrometheusHandle` to expose its inner metrics store in order to not store metrics twice?
* Something else?

Also regarding the ergonomics of the `PrometheusBuilder`, I found it difficult to get back the `PrometheusRecorder`, but also install the prometheus exporter to its own tokio task. I basically want the functionality of `PrometheusBuilder::install`, but have it return the `Recorder` instead of installing it. I can submit a PR with this functionality if it doesn't exist.

Regarding "Modify `PrometheusHandle` to expose its inner metrics store in order to not store metrics twice", I know that's maybe an unsavory idea because it starts exposing internal implementation details. Maybe keeping two separate Recorders and metrics registries is cheaper than I'm thinking, but it felt like a waste that I can't access that data directly when it's there.

Thanks for your time, and for this awesome crate!

**Comment by tobz** [comment]
Answering in no particular order:

> I found it difficult to get back the PrometheusRecorder, but also install the prometheus exporter to its own tokio task.

Once you "install" a global recorder, it is intentional that the only way to access it is as a `&'static dyn Recorder`. Trying to get back to the original type (i.e. `PrometheusRecorder`) is an anti-pattern. However, there's already [`PrometheusBuilder::build`](https://docs.rs/metrics-exporter-prometheus/latest/metrics_exporter_prometheus/struct.PrometheusBuilder.html#method.build) and [`PrometheusBuilder::build_recorder`](https://docs.rs/metrics-exporter-prometheus/latest/metrics_exporter_prometheus/struct.PrometheusBuilder.html#method.build_recorder) for building the recorder/HTTP server future, or just recorder, respectively

> I'm now wanting to expose those same metrics to other parts of my application.

Similar to the first point, but it's really an anti-pattern for a recorder to be exposing internal state unless that's the intent of the recorder. It would be one thing if the recorder's express purpose was to just act as a holding tank for data, and callers were expected to query the data themselves via a guard/handle type... but having the Prometheus exporter expose that would be conflating too many things in the same implementation.

If it was me, I would write a dedicated exporter that did what I described above, and basically provided thread-safe methods for querying and modifying the data: essentially, a wrapper over [`Registry`](https://docs.rs/metrics-util/latest/metrics_util/registry/struct.Registry.html). After that, as you mentioned, I'd use `Fanout` to send the metrics to both the Prometheus exporter and the in-memory exporter.

I'd support a PR for the type of recorder I described above, since I could see that having a lot of value. It would probably be possible, as well, to simply write a new guard/handle type that wraps over `Arc<Registry<K, S>>` and then actually implement `Recorder` for `Registry<K, S>` itself.

**Comment by bschwind** [comment]
@tobz  thanks for the answer

> Once you "install" a global recorder, it is intentional that the only way to access it is as a &'static dyn Recorder. Trying to get back to the original type (i.e. PrometheusRecorder) is an anti-pattern

I think I described it wrong - I can use `build` to get both the Recorder and the Future exporter, and then I can set the global Recorder, and also spawn the Future with tokio. But what I wanted was to get the Recorder (without having it installed for me) while having the metrics-exporter-prometheus crate spawn the exporter Future. I would then install the Recorder myself, perhaps after combining with other Recorders. Is that also an anti-pattern?

Also, my main worry was having two Registries processing and storing my metrics essentially twice in my application, but your suggestion makes it sound like this is fairly common and not very expensive to do, is that a fair assessment? If that's the case I'll go ahead with your suggestion and write my own Recorder alongside the prometheus one.

**Comment by tobz** [comment]
> I think I described it wrong - I can use `build` to get both the Recorder and the Future exporter, and then I can set the global Recorder, and also spawn the Future with tokio. But what I wanted was to get the Recorder (without having it installed for me) while having the metrics-exporter-prometheus crate spawn the exporter Future. I would then install the Recorder myself, perhaps after combining with other Recorders. Is that also an anti-pattern?

No, that makes sense... but I would still suggest to use `PrometheusBuilder::build`. There's already four methods related to installing/building the recorder (and potentially the HTTP client/server future) so adding yet another method feels like just too much.

The code to spawn the future will be a single line -- `tokio::spawn(server_future)` -- if you're already executing within a Tokio task, or you can just lift the code that `PrometheusBuilder::install` uses for spawning a background thread with the Tokio "current thread" runtime.

> Also, my main worry was having two Registries processing and storing my metrics essentially twice in my application, but your suggestion makes it sound like this is fairly common and not very expensive to do, is that a fair assessment? If that's the case I'll go ahead with your suggestion and write my own Recorder alongside the prometheus one.

I guess I wouldn't say it's _common_ to have two registries... generally metrics are for flowing out of an application to somewhere else, not for informing other parts of the same application/process. As such, usually a single exporter is selected to match up with whatever infrastructure is available and that's that.

Your assessment is fair, though, that it should still be reasonably performant to use two registries in a fanout pattern.

**Comment by bschwind** [comment]
> There's already four methods related to installing/building the recorder (and potentially the HTTP client/server future) so adding yet another method feels like just too much.

Okay, that's totally fine! Just wanted to make sure my assumptions weren't off. I was hoping for the convenience of `metrics-exporter-prometheus` spawning the future for me, but you're right that I can just lift the code from `install`.

> As such, usually a single exporter is selected to match up with whatever infrastructure is available and that's that.
> 
> Your assessment is fair, though, that it should still be reasonably performant to use two registries in a fanout pattern.

Noted! Thank you for the discussion, I think this clears up the questions I had. If I find a useful pattern for dealing with this issue, I'll open a PR.
