### ISSUE TITLE
failed to run custom build command for `metrics-exporter-tcp v0.8.0`

### ISSUE THREAD

**Issue by photino** [metrics-rs/metrics#363]
Our project [zino](https://github.com/photino/zino) has a dependency of `metrics-exporter-tcp`. When updating it to version 0.8.0, it fails to build. It works well for version 0.7.0.

![image](https://user-images.githubusercontent.com/3446306/232959674-ef25e2e7-85d0-4267-9050-7ed6badedef1.png)

**Comment by tobz** [comment]
Yes, this is due to a change in `prost` where `protoc` is no longer bundled with the crate, and build environments must provide it on their own.

You can follow the install instructions from the official `protobuf` repository: https://github.com/protocolbuffers/protobuf#protocol-compiler-installation
