### ISSUE TITLE
is counter macro supports floating point values?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [metrics-rs/metrics#367]

**Comment by tamasfe** [comment]
> 
> This is an intentional choice to ensure that counters are monotonically increasing, which would not be guaranteed if floating-point values were accepted, as negative values could be given, leading to the overall counter value decreasing.
> 
> If floating-point values are desired, gauges can be used instead, as helpers such as [`increment_gauge`](https://docs.rs/metrics/latest/metrics/macro.increment_gauge.html) already exist for working with gauges in a similar way to counters.

Guaranteeing positive values at the type-level is nice, however using a gauge and pretending it's a counter is not ideal. Prometheus has builtin features to deal with counter resets that are not available for gauge metric types (e.g. you cannot use the `rate()` function).

So in order to record total request times, you'd have to either:
- use integers and a smaller unit, this technically works but goes against prometheus' conventions
- use something like `deriv()` on the gauge, but this won't account for resets

These hacks could be avoided either by:

- allowing to override metric type (even in just the exporter), this is hacky but could work
- allowing `f64` counters, and clipping new values below `0` (or do nothing and leave negative values as a responsibility of the user)

**Comment by tobz** [comment]
@tamasfe It's unfortunate that our choice to constrain counters to `u64` has suboptimal interactions with that aspect of Prometheus, but it's not something I'm ever going to change in `metrics`.

If people are primarily interacting with Prometheus, and want an experience that matches the Prometheus conventions more closely, both the [`prometheus`](https://docs.rs/prometheus) and [`prometheus-client`](https://docs.rs/prometheus-client) crates are suitable replacements for `metrics`.

**Comment by tamasfe** [comment]
We've just switched from `prometheus` to use `metrics` due to the convenient API and the architecture and philosophy that is similar to `tracing`. I was confident that this issue could be easily resolved or worked around as the most (only?) widely used exporter seems to target Prometheus.

> that matches the Prometheus conventions more closely

It's not just Prometheus, OpenTelemetry also recently [chose](https://github.com/open-telemetry/opentelemetry-specification/issues/2977#issuecomment-1489150771) to recommend seconds as the unit of measurement for durations after a long debate.

> but it's not something I'm ever going to change in metrics.

I'd be happy to submit a PR for it.
