### ISSUE TITLE
metrics-exporter-prometheus should use units set by describe macro.

### ISSUE THREAD

**Issue by rukai** [metrics-rs/metrics#426]
## Feature request 1
The `describe_*!` macros set a unit for each metric but metrics-exporter-prometheus does not currently make use of it.
The prometheus protocol itself does not provide a way to set a unit however [it is documented](https://prometheus.io/docs/practices/naming/) that the correct way to handle units in prometheus is to postfix them to the end of the metric name.

So I propose that given a metric like:
```rust
describe_counter!("connections", Unit::Count, "The total count of opened connections")
register_counter!("connections"),
```
It will export as:
```prometheus
# HELP connections The total count of opened connections
# TYPE connections counter
connections_count{} 1
```

This will allow this library to be truly generic across different metrics protocols, as otherwise the user will need to duplicate unit information in other protocols in order to properly use prometheus.

This feature could be disabled in the prometheus builder if there are cases where the user only uses prometheus and needs greater control.

## Feature request 2

Additionally that same page mentions that applications should prefix metrics with the name of the application.
So maybe we should also have an optional setting in the prometheus builder to set the application name such that the previous export will now export as:
```
# HELP connections The total count of opened connections
# TYPE connections counter
application_connections_count{} 1
```

This follows the same reasoning as the previous feature, other protocols may not include the application name at the beginning of each name resulting in redundant information.

**Comment by tobz** [comment]
## Using the units that are captured in description information

In terms of using the specified units, the whole description API sort of needs a rework, mostly due to how rigid it currently is... but your point about following the Prometheus specification/recommendations and actually using it is sound. I would accept a PR for that.

## Prefixing metric names

As far as prefixing, that's also fair although the aforementioned Prometheus documentation, it mentions not only that it _should_ be prefixed (versus **must**) but also that you might not want a prefix across all metrics your application emits, specifically if client libraries are emitting their own.

This is most definitely the case with the overall model that `metrics` takes, so it could be a bit weird/repetitive to apply a prefix to all metrics, and then end up with something like `myapp_hyper_...`. There'd probably need to be a little more thought put into this, because it's not trivial to only prefix metrics from the "application" vs dependencies... and users can already take advantage of the [prefix layer](https://docs.rs/metrics-util/latest/metrics_util/layers/struct.PrefixLayer.html) to all a prefix to all metrics uniformly if they so desire.
