### ISSUE TITLE
Metrics registration regression in `main`

### ISSUE THREAD

**Issue by jpds** [metrics-rs/metrics#471]
I have this minimum reproducer code:

```rust
use metrics::gauge;
use metrics_exporter_prometheus::PrometheusBuilder;
use std::thread;
use std::time::Duration;

fn main() {
    let builder = PrometheusBuilder::new()
        .install()
        .expect("failed to install Prometheus recorder");

    gauge!("test").set(42);

    loop {
        thread::sleep(Duration::from_millis(10000));
    }
}
```

When I use the released version:

```
[dependencies]
metrics = "0.22.3"
#metrics = { git = "https://github.com/metrics-rs/metrics", branch = "main" }
metrics-exporter-prometheus = "0.14.0"
```

The metric is displayed:

```
$ curl localhost:9000/metrics
# TYPE test gauge
test 42
```

However, if I swap out the released version for `main#a143ef60` - nothing is returned.

**Comment by jpds** [comment]
On a closer inspection - `v0.22.3` is `main#a143ef60` - no idea why the HTTP endpoint isn't returning any data with the reproducer.

**Comment by tobz** [comment]
Sorry, I'm a little confused.

So it works if you use `metrics@v0.22.3` and `metrics-exporter-prometheus@v0.14.0`, and it works if you use `metrics@main` and `metrics-exporter-prometheus@main`... what's the combination of `metrics`/`metrics-exporter-prometheus` that _doesn't_ work?

**Comment by tobz** [comment]
OK, that makes sense.

Due to the global static used to hold the global recorder reference, you can't mix and match versions of `metrics`. In this case, you're registering metrics via `metrics@main`, and `metrics-exporter-prometheus@v0.14.0` is installing itself to `metrics@v0.22.x`. This means it never has a chance to see the registered metric because it's pointed at an entirely different global static.
