### ISSUE TITLE
Meter for core metrics?

### ISSUE THREAD

**Issue by sunng87** [metrics-rs/metrics#51]
Meter is a frequently used metrics for measuring throughput, for example, the QPS of our service. In coda-hale's original metrics library, there is [meter](https://metrics.dropwizard.io/4.1.0/manual/core.html#meters) that can report rate in 1-, 5-, 15- minutes. 

Is there any reason for the absence of meter? And is there any alternative solution to measure this type of metrics in current core primitives?

**Comment by tobz** [comment]
`metrics` specifically avoids trying to provide calculated metrics i.e. rate, etc, and instead focuses on the core primitives: counter, gauge, and histogram.

My personal approach here would be that I used a counter and incremented it every time I ran a query, etc, and had my monitoring system compute the rate for me based on that.

Theoretically, you could write your own formatter/exporter that takes the raw data and computes these rates and serves up the computed values, but that would be out-of-scope for `metrics`/`metrics-runtime` itself.

**Comment by sunng87** [comment]
Yes but actually meter shares many common feature with histogram. Both requires a buffer to hold data sample, both value is derived from the sample data. Yes, for histogram is requires some sorting, while in meter is calculated from average in a second. But I still believe they are very similar in terms of computation.

**Comment by tobz** [comment]
I think my main concern with this is that I'm not sure how the metric should be data modeled.

The existing types are meant to be as generic as possible.  For counters and gauges, that's easy, because there's only a single value.  For histograms, we made the decision to give back all of the raw points, rather than aggregate ourselves, because it forces the caller to pay a certain performance price, and we can easily write exporters/observers that do the aggregation for us.

With this new proposed type, we have to add back in a certain level of complexity, I think, to handle the fact that the value(s) would change over time, and keeping the computed values accurate.  On top of that, we have to consider what the API change would be to `metrics-core` and `metrics-facade`.

Meters, by definition, have a configuration of sorts -- the rate intervals to compute -- and `metrics-facade` has no concept (and, I believe, shouldn't) of configuring a metric, only recording them.  We'd also have to consider what the signature should look like for observing a meter via the `metrics-core` traits.  

I don't think these are insurmountable, but I'd like to nail down what this would look like, and figure out if this can be done in a way that lets each component be as generic and composable as possible.

**Comment by raultang** [comment]
Thanks @tobz making the great library.
If we have QPS/TPS metrics, and for histogram if I can set the TimeUnit would be advanced.

**Comment by tobz** [comment]
Going to close this one.

While I know people probably still want a native "meter" type, I'm still of the opinion that it would involve an unnecessary amount of complexity, and given the support for defining units, this provides a pathway for exporters to be written that can support collecting/processing the raw data in whatever way is needed to generate meters.
