### ISSUE TITLE
Reset Histogram

### ISSUE THREAD

**Issue by xd009642** [metrics-rs/metrics#525]
Copied from discord so it doesn't get lost since it's been a few days:

So here's a mildly niche one, for coutners and gauges I can set them back their default values, but for histograms is there a way to do it? I currently have some warmup code before my service starts listening to a port and the histogram metrics for that code are guaranteed to be in like the 99.999th percentile so I want to ideally remove them from the measurements as they won't be a request a user sees (unless something goes very wrong)

and I kinda don't want to just duplicate that code with the metrics stuff taken out or pass some parameters down a chain to disable the metrics at that point. I'd rather just reset the histogram after warmup.

**Comment by tobz** [comment]
Sorry for the late reply on this one.

I can't see us adding an API to make this possible. The emission side of things (code actually incrementing counters, recording histogram samples, etc) shouldn't have control over resetting metric values.

The best solution I can think of is simply delaying when you install the global recorder, as this requires no changes at all to the code emitting the metrics, because feels like it might be reasonably achievable if you already have a point in the code where you could be adding a line to reset the metric values anyways.
