### ISSUE TITLE
Generic recorder interface

### ISSUE THREAD

**Issue by msmoiz** [metrics-rs/metrics#529]
The recorder interface seems to be primarily catered for a metrics setup that targets Prometheus or something like it. This makes it awkward to integrate with other metrics platforms like CloudWatch that do not natively support the metric types defined in this crate.

For instance, to publish a metric to CloudWatch, you need to first map it to a counter, gauge, or histogram (distinctions that do not necessarily matter to CloudWatch in the way they do to Prometheus) and then map back to the more generic interface that CloudWatch uses (time-specific datapoints) in the exporter.

Even platforms that recognize these metric types do not always define them in the same way, e.g., a counter can only increase in Prometheus but can increase or decrease in Datadog. It is also harder to scale this approach, as any platform-specific metric type that a user might want to export needs to be defined here as well as in the exporter (as opposed to just the exporter).

Looking around at the broader ecosystem, my perception is that metrics are fundamentally just time series data (i.e., a value and a timestamp), and the metric types defined by Prometheus, Datadog, and other solutions are specific aggregations on those time series (e.g., counter = sum(datapoints in time period) in Datadog). It would be nice to have a more generic recorder interface that focuses on emitting that common denominator, a value and a timestamp, and leaves the work of aggregating it in platform-specific ways to the exporter(s). This lines up with the way the log crate handles logging, which I think serves as a useful analog.

```rust
metric!("requests_served", 1);
```

**Comment by tobz** [comment]
You're certainly correct that the API is it exists aligns fairly well with Prometheus... but it also aligns with the vast majority of metrics systems. People work with counters, gauges, and histograms/distributions. They don't write observability code thinking about `(timestamp, value)` tuples. At the end of the day, that may very well be exactly how the metrics are stored, but boiling down the `metrics` API to map to that would be, at best, confusing: "do I use `counter!` or `metric!`? why do I need to know the difference?", etc.

There's nothing stopping a CloudWatch exporter for `metrics` from simply emitting every single update to a counter, gauge, or histogram as a single datapoint. Maybe that feels weird, because users are making the decision twice -- pick a metric type when emitting it, then pick it again when querying -- but that feels like like a failing of CloudWatch's UX to me than anything else.

If there are specific issues that you encounter in attempting to accomplish this, I'd be happy to see issues opened for those, but to say it out loud, since I think there's an implicit ask here: I'm not willing to add a metric type-less method/macro, as described in your post, to `metrics`.
