### ISSUE TITLE
Allow updating a counter to a fixed value

### ISSUE THREAD

**Issue by RAnders00** [metrics-rs/metrics#81]
There are cases where a counter is the semantically right choice, but instead of counting it up ourselves the application has to poll this counter value from somewhere else.

My particular use case that would call for this is collecting a process' CPU times from the operating system. (How many seconds of CPU time has this process spent running on the CPU since its start?) - This metric can then be processed later by the metrics system and converted into percent cpu usage. This way of counting CPU load seems to be common, e.g. [see here](https://github.com/siimon/prom-client/blob/master/lib/metrics/processCpuTotal.js)

Two issues are present here: First, the amount of seconds is a continuum - there are no discrete increments. (However that issue is discussed in #60).
The second issue I want to highlight here is that this amount of seconds is polled from the operating system, and is typically returned as a fixed value that the OS has counted "for you" since the start of the process. Essentially this means you end up periodically running a polling function against the operating system, and then have some amount of seconds that you would want to **update** a counter to be.

Currently, one has to track the difference between invocations of the polling routine and the use `counter!` to increment the counter, which is cumbersome.

**Comment by tobz** [comment]
If you're using `metrics-runtime`, there's `Sink::proxy` exactly for this sort of scenario: https://docs.rs/metrics-runtime/0.13.1/metrics_runtime/struct.Sink.html#method.proxy

There's no comparable macro for doing the same thing, or for setting a counter directly.  It's possible we'll add this in the future but no guarantees.  It has some implications for how particular protocols would function, in particular protocols where doing an operation on a counter is intended to be the amount to increment by, not the absolute value.

**Comment by tobz** [comment]
I'm going to close this issue as a "won't change", with some color as to why.

We're making a conscious decision that using `metrics` as a proxy layer for existing metrics is an unsupported use case.  Now, obviously, it's possible to use it to do so, but it may come with caveats like this very issue, where the desire to do something may not line up with what `metrics` supports.

In my view, I think this is a reasonable place to use gauges, rather than counters.  I understand that, semantically, counters may make more sense here, but I'm not sure I'm willing to add further methods to the core traits to support this very niche use case where gauges would otherwise suffice.

On top of that, there's an issue of floating point values, as you brought up by linking to #60.  We rely on counters being unsigned integers so that we can enforce monotonicity at compile-time, and using floating-point integers would shift that to a runtime check, which isn't a change I'm willing to consider at this time.

**Comment by tobz** [comment]
There's some renewed activity around this topic in #172 based on improvements we've made in `metrics` 0.13 that allow us to inject logic to the pipeline without having to necessarily extend the macros themselves.

Going to reopen this for now for tracking purposes.
