### ISSUE TITLE
http exporter failures can't be detected at startup

### ISSUE THREAD

**Issue by mellon85** [metrics-rs/metrics#83]
The changes discussed here are in PR #83 

While trying to setup a Receiver I am encoutering a issue with the current design of the async_run implementaiton.
As async_run will block the current task it's going to be executed in a spawned task (i.e. `tokio::spawn(async `{setup_metrics().await})`).
If it's spawned in a task though I have no way to detect it the exporter succesfully bound itself to the port, as it will trigger a panic in the task asynchronously.

```rust
async fn setup_metrics(metrics_addr: &str) {
    let receiver = metrics_runtime::Receiver::builder()
        .build()
        .expect("Failed to created a receiver");

    let exporter = HttpExporter::new(
        receiver.controller(),
        PrometheusBuilder::new(),
        metrics_addr.parse().unwrap(),
    );
    receiver.install();
    exporter.async_run().await.expect("Exporer failed");
}
```

Shouldn't `async_run` be not `async` and insted return a future to await on?  Instead of

```rust
Server::bind(&self.address).serve(make_svc).await
```

It should return something  like
```rust
Box::new(Server::bind(&self.address).serve(make_svc))
```
and the caller will receive a future only if the binding works

**Comment by tobz** [comment]
So this problem is interesting because yeah, there's no great way to separate the failures to bind to the address and the actual result of running the server future to completion.

Ignoring that for a second, though, your PR is not required here.  You can simply bind the async function to a local variable before passing it off to a task:

    async fn setup_metrics(metrics_addr: &str) {
        ...

        let runner = exporter.async_run();
        tokio::spawn(async move { let _ = runner.await; });
    }

That satisfies your desire to catch the panic during initialization rather than it being swallowed by the task.

The exporter API surface is something we're tweaking and improving as part of metrics v2 work happening in #80.  I will make a note to visit this specific area of the exporter building process to see if we can come up with a better option than simply `panic`-ing because of an inability to bind to the listen address.

I'm going to close this but if you feel like I missed an aspect of your question/ask, we can continue chatting. 👍

**Comment by mellon85** [comment]
The solution you propose doesn't really work, an async function is not executed until it's awaited, so calling `async_run` won't bind the port until inside the task again.

Reproducible with

```rust
use metrics_runtime::{exporters::HttpExporter, observers::PrometheusBuilder};
use tokio::task;

async fn setup_metrics() {
    let receiver = metrics_runtime::Receiver::builder()
        .build()
        .expect("Failed to created a receiver");

    let exporter = HttpExporter::new(
        receiver.controller(),
        PrometheusBuilder::new(),
        "0.0.0.0:50".parse().unwrap(),
    );
    receiver.install();
    let runner = exporter.async_run();
    task::spawn(async move {
        let _ = runner.await;
    });
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    setup_metrics().await;
    println!("Not panicked");
    Ok(())
}
```

**Comment by tobz** [comment]
Yeah, you're right.  That's what I get for responding to issues tired. :)

I'll have to think a little more about this.  I'm not a fan of returning boxed futures in public APIs, and I think we can likely come up with a better solution there.

**Comment by tobz** [comment]
Closing this issue as we've updated the Prometheus exporter in #92, where we now attempt to bind to the listening address early before spawning the server or handing back the future which drives it.

This won't be backported to 0.12 as we're now working towards a 1.0 release in the very near future, and is currently only available on `main`, although I'll likely cut new alpha releases of all crates within a week, which will include this change.
