### ISSUE TITLE
JSON and YAML observer silently drop metrics

### ISSUE THREAD

**Issue by luke-clifton** [metrics-rs/metrics#86]
If you have

```
counter!("a", 1);
counter!("a.b",1);
```

Both the JSON and YAML observers will only emit the `"a"` metric, and `"a.b"` will be dropped (or vice-versa). The prometheus observer does the correct thing.

I can't find this behaviour documented anywhere.

To fix this would require changing the JSON and YAML output format. (Or providing an alternative, and deprecating the old one to not break things).

**Comment by tobz** [comment]
Argh, yeah, this must be a consequence of how we handle separators. (the periods). Definitely not intended for it to break in such a way.

If you have a fix in mind, I'm all ears.  I'm not sure the output format has to change, since if my memory is serving me correctly here, it may suffice simply to alter how we deal with the tokenization used to build the tree structure.

**Comment by tobz** [comment]
Closing this as it's very old and the code example at hand is no longer relevant given how we've moved on with the current crates.
