### ISSUE TITLE
Specifying options for each metric

### ISSUE THREAD

**Issue by Marwes** [metrics-rs/metrics#96]
Are there any recommendations for how to specify options on a per metric basis?

For cloudwatch we currently have two "options", dimensions and units and this is specified through the labels that are sent with each metric. Originally we only had dimensions and since this is already a key-value mapping it seemed natural to directly use labels for this mapping.

However, with https://github.com/ramn/metrics_cloudwatch/pull/18 I would also like the unit of the metric to be possible to specify and for this I hacked it in by assuming that an `@unit` label specifies this unit, instead of specifying an `@unit` dimension.

This isn't great though so I was wondering if there is a better way? Or if the metrics crate could offer more for this case?

**Comment by Marwes** [comment]
One idea would be to pass a`&[&dyn std::any::Any]`.

```rust

fn record_metric(&self, ..., options: &[&dyn Any]) {
    for option in options {
        if let Some(unit) = option.downcast::<metrics_cloudwatch::Unit>() {
            // Use the option
        }
    }
}
```

**Comment by tobz** [comment]
I think an anymap, or any other sort of map, is probably a step too far in the API.  Aside from that, it also presents an issue with how you would deal with metrics emitted from libraries that aren't under your control.

For example, what happens if a time-related metric is emitted from an internal library with no units specified, either through the name itself or through the proposed options sidechannel?

My suggestion here -- and this is specific to the stuff sitting in `main` which will soon become part of the 1.0 release -- would be that you continue to use labels, because they're an existing sidechannel and exporters can handle them however they choose.  On top of that, there's a new [`Layer`](https://docs.rs/metrics-util/0.4.0-alpha.3/metrics_util/layers/index.html) stack that we've introduced which allows users to insert custom logic between where metrics are emitted and when they make it to the installed exporter.

This would provide an insertion point where you could do more complicated logic, such as adding a new `@unit` label based on a default i.e. if you know your default for time durations is going to be nanoseconds, or filtering metrics from a particular library and adding units/dimensions to them to fit your system.

I'll leave the issue open for now while I think a little more on it but right now I'm not seeing enough value in the proposal to change the API as such.

**Comment by Marwes** [comment]
2 cents

>  Aside from that, it also presents an issue with how you would deal with metrics emitted from libraries that aren't under your control.

I'd expect them to just ignore them, unless `unit` (or any other option) are built into the metrics crate itself. Using `unit` as an example, it is perfectly fine to ignore it, it just helps the backend understand and display it better. In this instance I may not even have needed the unit however the `metrics` crate only supports integers for `value!` (histogram) and when updating our code to use `metrics_cloudwatch` I had to change some metrics that transmitted a float of megabytes into an integer of bytes to keep things consistent.

> This would provide an insertion point where you could do more complicated logic, such as adding a new @unit label based on a default i.e. if you know your default for time durations is going to be nanoseconds, or filtering metrics from a particular library and adding units/dimensions to them to fit your system.

Well for units I would want them to be specified where the metric is emitted, otherwise I could always specify, say `latency => milliseconds` when initializing the recorder, but that would easily fall out of sync. A layer wouldn't really help unless it is explicitly aware of the inner recorder (say `metrics_cloudwatch`). Otherwise it is still stuck with forwarding to the same `Recorder` interface.

**Comment by tobz** [comment]
I could be amenable to providing a hook in the registration methods -- i.e. [`Recorder::register_counter`](https://docs.rs/metrics/0.13.0-alpha.3/metrics/trait.Recorder.html#tymethod.register_counter) -- where a unit could be passed.  This would be an enum that `metrics` itself exposes.  Confusion over units and how to represent them downstream of the emission call site has occurred in the past, so if that's the crux of the issue here, we could potentially make it a first-class citizen.

Would you be willing to work on this if I provided guidance on how I roughly wanted things to look?
