### ISSUE TITLE
Parse metrics with constant keys/labels in macros

### ISSUE THREAD

**Issue by Bathtor** [metrics-rs/metrics#97]
Currently an invocation like `increment!(my_labels::METRIC_KEY, my_labels::METRIC_LABEL => label_value);` will fail to parse in the macro (e.g., "expected literal" or "unexpected token").

It would be nice if using string constants would in these positions would be an option, so I don't have to repeat string literals in a bunch of places if the same metric can be produced from multiple sources (e.g. multiple different implementations of the same trait).

**Comment by tobz** [comment]
Yeah, seems pretty reasonable!

Right now the procedural macros are matching directly on literal strings, but maybe there's a way to match on constant expressions?  As long as we can evaluate and determine that an expression is in fact constant, it should be safe to use.

Open to PRs if you're interested in looking into this, otherwise it'll likely take some time to get picked up and worked on.

**Comment by Bathtor** [comment]
Yeah, it may be problematic to support the check for legal characters like this, since you probably can't evaluate a constant expression in a macro, even if you can figure out that it is one (which I'm not 100% on either, tbh).

Anyway, it's more of a nice to have, really. No rush :)

**Comment by tobz** [comment]
So I spent some time looking into this.  Indeed, it doesn't seem like proc macros have a way to distinguish an expression _referencing_ a constant, and thus don't have a way to peek into them for slurping out the constant itself.

One thought I had that was we could potentially newtype the metric name such that it wraps a `&'static str` directly, and provide a helper macro to generate them.  The main metric macros would still accept literal strings (or this newtype) and do the right thing i.e. checking string literals for conformance, etc.  The helper macro would emulate that and thus we could keep metric name conformance checking while still allowing you to const-ify these things for cleanliness/code reuse/whatever.

I'll have to spend some more time on it, but would that work for you?  Essentially, you'd end up with something like:

    const METRIC_KEY: MetricName = name!("metric_key");

**Comment by Bathtor** [comment]
Yeah, that'd work well I think. Even cleaner to read, perhaps, then just having `&str` constants for metric labels.

**Comment by tobz** [comment]
Cleaning up some old issues, so swinging back around here...

It should be possible to use a constant in the key name position as-is, although labels cannot (yet) use constants for the key portion of a label.  I'll be opening a PR to rectify that shortcoming.

This all comes with the same caveat that due to the reasons explained above, using constants means that there will be some allocations because procedural macros can't see "through" an ident -- i.e. `MY_CONST` -- to know that it, for example, points to a string literal or `&'static str`.  Additionally, there is no ability to specify constant functions in traits, so there's no pathway to specialized trait implementations to allow autowiring of these const-vs-not-const conversions without the procedural macros being aware of what's going on.

Additionally, with the merging of #260, constants can also be used for metric descriptions now.  That PR, however, does not yet have a release.

**Comment by tobz** [comment]
This is now released as part of `metrics@v0.18.0`.
